"""empty message

Revision ID: 467e37270665
Revises: 7e831f520ddb
Create Date: 2018-09-17 09:05:48.802495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467e37270665'
down_revision = '7e831f520ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'posted')
    # ### end Alembic commands ###
