"""empty message

Revision ID: 500fcd828cb0
Revises: b1d78301555d
Create Date: 2018-09-15 21:37:32.980155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500fcd828cb0'
down_revision = 'b1d78301555d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('post', sa.String(length=10000), nullable=True))
    op.add_column('blogposts', sa.Column('title', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'title')
    op.drop_column('blogposts', 'post')
    # ### end Alembic commands ###
