"""empty message

Revision ID: 859dcbdf7a17
Revises: 0f9dafcda7a9
Create Date: 2018-09-15 23:31:08.328971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859dcbdf7a17'
down_revision = '0f9dafcda7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('pic_path', sa.String(), nullable=True))
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogposts', 'pic_path')
    # ### end Alembic commands ###
