"""empty message

Revision ID: b1d78301555d
Revises: 78238e6d4d50
Create Date: 2018-09-15 21:36:49.414566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d78301555d'
down_revision = '78238e6d4d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogposts', sa.Column('summary', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'summary')
    # ### end Alembic commands ###
